# Pre-commit hooks configuration for survival framework
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  # Python code formatting with black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']
        files: ^(src|tests)/.*\.py$

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        files: ^(src|tests)/.*\.py$

  # Linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length=100'
          - '--extend-ignore=E203,W503,E501'
          - '--max-complexity=10'
        files: ^(src|tests)/.*\.py$
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-strict-optional']
        files: ^src/.*\.py$
        additional_dependencies:
          - types-setuptools
          - pandas-stubs

  # Docstring coverage check
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ['-vv', '--fail-under=80', 'src/']
        pass_filenames: false

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
        files: ^src/.*\.py$

  # Check for common Python mistakes
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          - '--disable=C0111,R0903,C0103'
          - '--max-line-length=100'
        files: ^src/.*\.py$
        additional_dependencies:
          - pandas
          - numpy
          - scikit-learn
          - scikit-survival
          - lifelines
          - mlflow

  # Jupyter notebook cleaning (if using notebooks)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: \.ipynb$

  # Auto-sync METHODOLOGY.docx when METHODOLOGY.md changes
  - repo: local
    hooks:
      - id: sync-methodology-docx
        name: Sync METHODOLOGY.docx from METHODOLOGY.md
        entry: python scripts/md_to_docx.py
        language: system
        files: ^METHODOLOGY\.md$
        pass_filenames: false
        stages: [commit]

# Configuration for individual tools
default_language_version:
  python: python3.11

# Exclude patterns
exclude: |
  (?x)^(
      \.git/|
      \.venv/|
      venv/|
      __pycache__/|
      \.pytest_cache/|
      \.mypy_cache/|
      src/mlruns/|
      src/artifacts/|
      src/models/|
      data/test_outputs/|
      survival_framework_v_1\.py
  )$
